### ISSUE TITLE
USER STORY: View basket

### ISSUE THREAD

**Issue by Kathrin-ddggxh** [Kathrin-ddggxh/chirpy_chooks#14]
As a **site user** I can **easily access my shopping basket** so that I can **review its contents and updated total cost**

## Acceptance Criteria

- [ ] Link to shopping basket accessible on all pages 
- [ ] Basket displays list of selected items and total cost
- [ ] Items in basket show quantity and subtotal 

## Tasks

- [ ] 
- [ ] 
- [ ]
