### ISSUE TITLE
USER STORY: Payment

### ISSUE THREAD

**Issue by Kathrin-ddggxh** [Kathrin-ddggxh/chirpy_chooks#16]
As a **site user** I can **enter my personal and payment details in the checkout form** so that I can **easily pay for my order**

## Acceptance Criteria

- [ ] Secure checkout form
- [ ] Inputs labelled clearly, including required fields  

## Tasks

- [ ] Use Stripe for payment feature
