### ISSUE TITLE
USER STORY: Delete product (admin)

### ISSUE THREAD

**Issue by Kay-ddggxh** [Kathrin-ddggxh/chirpy_chooks#22]
As a **Admin User** I can **delete existing products from the shop** so that I can **avoid listing unavailable or discontinued items**

## Acceptance Criteria

- [x] Delete product option only accessible to admin user
- [x] Request user confirmation before deleting product

## Tasks

- [x] Add delete link to product details page
- [x] Protect delete button by asking user to confirm action
