### ISSUE TITLE
USER STORY: Social media links

### ISSUE THREAD

**Issue by Kathrin-ddggxh** [Kathrin-ddggxh/chirpy_chooks#23]
As a **site user** I can **easily find links to the shops social media presences** so that I can **find out about activity not showing on the website**

## Acceptance Criteria

- [ ] Footer with obvious social media icons
- [ ] Include link to shop's Facebook page 
- [ ] Links open in new tab 

## Tasks

- [ ] Create footer with icons in base template 
- [ ] Use fontawesome or iconify to render icons 
- [ ] Include noopener and noreferrer attribute in anchor tags
