### ISSUE TITLE
USER STORY: GDPR compliance

### ISSUE THREAD

**Issue by Kathrin-ddggxh** [Kathrin-ddggxh/chirpy_chooks#25]
As a **site user** I can **view a privacy policy** so that I can **have full information on my rights concerning the use of my data and privacy laws**

## Acceptance Criteria

- [ ] Easily accessible link to privacy policy 
- [ ] Policy is concise and transparent

## Tasks

- [ ] Include link to policy document 
- [ ] Generate privacy policy using online generator
