### ISSUE TITLE
USER STORY: GDPR compliance

### ISSUE THREAD

**Issue by Kay-ddggxh** [Kathrin-ddggxh/chirpy_chooks#25]
As a **Site User** I can **easily access a privacy policy** so that I can **read about how my personal data is being handled**

## Acceptance Criteria

- [x] Privacy policy obvious to user and easily accessible

## Tasks

- [x] Generate policy with online generator
- [x] Link to policy in seperate page or pop-up
