### ISSUE TITLE
USER STORY: Delete/Edit forum posts

### ISSUE THREAD

**Issue by Kathrin-ddggxh** [Kathrin-ddggxh/chirpy_chooks#29]
As a **registered site user** I can **delete or edit my previous posts** so that I can **manage my activity in the forum**

## Acceptance Criteria

- [ ] Delete and edit option only accessible to registered users 
- [ ] Option only displaying on post that were submitted by authenticated user 
- [ ] Clear and obvious labelling of delete and edit buttons 

## Tasks

- [ ] 
- [ ] 
- [ ]
