### ISSUE TITLE
USER STORY: Navigation

### ISSUE THREAD

**Issue by Kathrin-ddggxh** [Kathrin-ddggxh/chirpy_chooks#3]
As a **user** I can **see a responsive navbar at the top** so that I can **navigate the site easily**

## Acceptance Criteria

- [] Responsive navbar
- [] Descriptive links
- [] Logo as default home button

## Tasks

- [] Use bootstrap responsive nav element with burger drop-down
- [] Name links clearly and intuitively
- [] Link logo to home page
