### ISSUE TITLE
USER STORY: Account registration

### ISSUE THREAD

**Issue by Kathrin-ddggxh** [Kathrin-ddggxh/chirpy_chooks#5]
As a **site user** I can **register an account** so that I **can have a personal profile and contribute to the forum**

## Acceptance Criteria

- [ ] Secure sign up feature lets user create account 

## Tasks

- [ ] Install Django Allauth 
- [ ] Customise sign up page
