### ISSUE TITLE
USER STORY: Login/Logout

### ISSUE THREAD

**Issue by Kathrin-ddggxh** [Kathrin-ddggxh/chirpy_chooks#6]
As a **site user** I can **easily login or logout** so that I **utilise features reserved for registered users and access my account information**

## Acceptance Criteria

- [ ] Login feature allows user to log into account and use all site functions
- [ ] Feature allows user to log out of account

## Tasks

- [ ] Utilise previously installed Django Allauth 
- [ ] Customise login/logout page
