### ISSUE TITLE
USER STORY: Password recovery

### ISSUE THREAD

**Issue by Kay-ddggxh** [Kathrin-ddggxh/chirpy_chooks#7]
As a **registered Site User** I can **click "Forgot Password" in login form** so that I can **recover my login credentials**

## Acceptance Criteria

- [x] "Forgot Password"-link in login form
- [x] Recovery email with link to reset password page

## Tasks

- [x] Utilise Allauth functionality to handle password reset option
