### ISSUE TITLE
USER STORY: Confirm registration

### ISSUE THREAD

**Issue by Kay-ddggxh** [Kathrin-ddggxh/chirpy_chooks#8]
As a **Site User** I will **receive an email confirming my registration** so that I am  **sure my account was created successfully**

## Acceptance Criteria

- [x] Confirmation email sent to user after signing up
- [x] Verification link in email

## Tasks

- [x] Use Gmail for real live email sending functionality
